config/routes.rb
BgiApp::Application.routes.draw do
  devise_for :users, :controllers => {:registrations =>  'registrations', :omniauth_callbacks => "users/omniauth_callbacks"}, :path => 'auth', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  devise_scope :user do
     post '/auth/mobile_signin', :to => 'registrations#mobile_signin'
  end
  root 'pages#home'
  get 'home', :to => 'pages#home'
  get '/contact', :to => 'pages#contact'
  get '/about', :to => 'pages#about'
  get '/help', :to => 'pages#help'

  get '/country/:iso', :to => 'countries#fetch',  :defaults => {:format=>'json'}
  get '/fetch_countries', :to => 'countries#fetch_all', :defaults => {:format => 'json'}

  get '/fetch_states/:cid', :to => 'states#fetch_by_cid', :defaults => {:format => 'json'}

  post '/log/submit', :to => 'calllogs#submit'
  get 'log/list', :to => 'calllogs#list'

end

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<% if user_signed_in? %>
			<li>Logged in as <%= current_user.fname %> </li>
			<li><%= link_to "Logout", destroy_user_session_path, :method => :delete, :class => 'navbar-link' %> </li>
			<% else %>
			<li><%= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2) %></li>
			<li><%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %></li>
			<% end %>
		</ul>
	</nav>
	<% unless notice.nil? %><p class="notice"><%= notice %></p> <% end %>
    <% unless alert.nil? %><p class="alert"><%= alert %></p> <% end %>
</header>

app/views/layouts/_scripts.html.erb
<!-- Javascripts -->
<%= javascript_include_tag :application %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js">
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]>
	<%= stylesheet_link_tag 'blueprint/ie' %>
<!--[endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= csrf_meta_tags %>
  <meta charset=”utf-8”> 
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<section class="round">
			<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
	</div>
	<%= render 'layouts/scripts' %>
</body>
</html>